### ISSUE TITLE
色を着ける -> 色を付ける

### ISSUE THREAD

**Issue by itkrt2y** [igrep/igreque.info#5]
平仮名の方が一般的かな・・・

**Comment by itkrt2y** [comment]
`(1)を着けた` の所もですね

**Comment by igrep** [comment]
「着色料」といった単語からの推測でそうしていましたが...。
なるほど。無難にひらがなにしますか。

**Comment by igrep** [comment]
conflictが怖いので https://github.com/igrep/igreque.info/pull/4 のブランチから更に切ります。

**Comment by igrep** [comment]
すでにリリースしたのでcloseします。
報告ありがとうございました！
